name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        include-prerelease: true
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: |
        dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test Test/Test.csproj --no-build --verbosity normal --configuration Release --logger "trx;LogFileName=test-results.trx" --results-directory ./TestResults --collect:"XPlat Code Coverage"
      
    - name: List test results (debug)
      if: always()
      run: |
        echo "Contents of TestResults directory:"
        ls -la TestResults/ || echo "TestResults directory not found"
        echo "Looking for TRX files:"
        find . -name "*.trx" -type f || echo "No TRX files found"
      
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: .NET Test Results
        path: 'TestResults/*.trx'
        reporter: dotnet-trx
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          TestResults/*.trx
          TestResults/**/*
        retention-days: 7